### ISSUE TITLE
error fish: Unknown command '_old_fish_prompt'  active.fish

### ISSUE THREAD

**Issue by kevinbin** [pypa/virtualenv#480]
(pelican)
fish: Unknown command '_old_fish_prompt'
/Users/hongbin/Workbench/Virtualenvs/pelican/bin/activate.fish (line 57): _old_fish_prompt
                                                                          ^
in command substitution
    called on line 69 of file '/Users/hongbin/Workbench/Virtualenvs/pelican/bin/activate.fish',

in function 'fish_prompt',
    called on standard input,

in command substitution
    called on standard input,

mac os 10.9 GM
virtualenv version  (1.10.1)
fish shell 2.0

**Comment by malthejorgensen** [comment]
This happened to me when I had already activated the virtualenv _before_ starting my tmux session, and then trying to activate the virtualenv (`. .venv/bin/activate.fish`) from inside the tmux session.

Fixed it by first starting the  tmux session, and then activating the virtualenv inside the session.

**Comment by fake-name** [comment]
This seems to still be occuring. And it's not tmux specific, and @mqsoh's fix doesn't work, either:

```
durr@wlntest ~> cd /media/Storage/Scripts/wlnupdates/
durr@wlntest /m/S/S/wlnupdates> . ./flask/bin/activate.fish
/tmp/.psub.4H6pimsyBu (line 1): Missing end to balance this function definition
function _old_fish_prompt
^
from sourcing file /tmp/.psub.4H6pimsyBu
        called on line 230 of file /usr/share/fish/config.fish

in function '.'
        called on line 50 of file ./flask/bin/activate.fish

from sourcing file ./flask/bin/activate.fish
        called on line 230 of file /usr/share/fish/config.fish

in function '.'
        called on standard input

source: Error while reading file '/tmp/.psub.4H6pimsyBu'
fish: Unknown command '_old_fish_prompt'
./flask/bin/activate.fish (line 1):
_old_fish_prompt
^
in command substitution
        called on line 55 of file ./flask/bin/activate.fish

in function 'fish_prompt'
        called on standard input

in command substitution
        called on standard input

(flask)
fish: Unknown command '_old_fish_prompt'
./flask/bin/activate.fish (line 1):
_old_fish_prompt
^
in command substitution
        called on line 55 of file ./flask/bin/activate.fish

in function 'fish_prompt'
        called on standard input

in command substitution
        called on standard input

(flask)
```

**Comment by johnww2** [comment]
I think this happens because in the cases where activate.fish attempts to substitute in a new fish function, it does not provide an "end" to balance the start of the function scope (although it wraps the whole thing in a begin/end blocks.)

I added a printf "end" and this seems to fix it.  (Note there are 2 such function definitions to fix)

example modified version:

`  # save the current fish_prompt function as the function _old_fish_prompt
    . ( begin
            printf "function _old_fish_prompt\n\t#"
            functions fish_prompt
            printf "\nend"
        end | psub )
`

**Comment by alexmitelman** [comment]
The issue is definitely still exists.
I have an open iTerm session, opening the project in VSCode shows this error in the integrated terminal.

**Comment by adammarples** [comment]
Still happening for me, and I'm using Pyenv 3.6.8 venv so Python 3.6 doesn't fix the issue

**Comment by touilleMan** [comment]
same thing here:

```fish
$ uname -a
Linux slipfast 4.18.0-16-generic #17pop0-Ubuntu SMP Fri Mar 8 17:52:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Pop!_OS 18.10
Release:	18.10
Codename:	cosmic
$ fish --version
fish, version 2.7.1
$ python3 --version
Python 3.6.7
$ python3 -m venv venv
$ . ./venv/bin/activate.fish 
functions: Function “_old_fish_prompt” does not exist
./venv/bin/activate.fish (line 18): 
        functions -c _old_fish_prompt fish_prompt
        ^
in function “deactivate”
	called on line 30 of file ./venv/bin/activate.fish
	with parameter list “nondestructive”

from sourcing file ./venv/bin/activate.fish
	called on line 230 of file /usr/share/fish/config.fish

in function “.”
	called on standard input

functions: Type “help functions” for related documentation

functions: Function “fish_prompt” does not exist
./venv/bin/activate.fish (line 47): 
    functions -c fish_prompt _old_fish_prompt
    ^
from sourcing file ./venv/bin/activate.fish
	called on line 230 of file /usr/share/fish/config.fish

in function “.”
	called on standard input

functions: Type “help functions” for related documentation

_old_fish_prompt: command not found
./venv/bin/activate.fish (line 21): 
        _old_fish_prompt
        ^
in function “fish_prompt”
	called on standard input

in command substitution
	called on standard input

(venv) 
```

Funny enough, starting a new fish shell display that I'm still in a virtual env (and environment variables configured by activate.fish are still set):
```fish
$ which python3
/home/emmanuel/projects/parsec-cloud/venv/bin/python3
$ fish
$ which python3
/home/emmanuel/projects/parsec-cloud/venv/bin/python3
$ set  | grep VIRTUAL
VIRTUAL_ENV /home/emmanuel/projects/parsec-cloud/venv
_OLD_VIRTUAL_PATH '/usr/local/sbin'  '/usr/local/bin'  '/usr/sbin'  '/usr/bin'  '/sbin'  '/bin'…
```

My guess is something is causing environ variables (hence virtualenv environ variables) to be shared across all fish instances (instead of beeing only provided to child processes).
Given the first thing activate.fish tries to do is to desactivate a possible previous it is 

The solution for me has to be to manually remove the following environ variables:
```fish
$ set -e _OLD_FISH_PROMPT_OVERRIDE 
$ set -e _OLD_VIRTUAL_PYTHONHOME
$ set -e _OLD_VIRTUAL_PATH
$ . ./venv/bin/activate.fish
(venv) $
```

**Comment by jlugao** [comment]
this is also happening to me

**Comment by seankelly** [comment]
The issue is the code assumes the output of `functions some_function` has this output:
```
> functions foo
function foo
        printf 'some prompt'
end
```

This is true when defined at the command line. But when the function is source from a file or via `psub`, it's instead this:
```
> functions foo
# Defined in prompt.fish @ line 1
function foo
        printf 'something prompt'
end
```

I changed the two `functions something_fish_prompt` calls to be this.
```
functions _old_fish_prompt | sed -e '/^function/ s/^/#/'
```

**Comment by weaming** [comment]
I fixed this after remove old virtualenv and create new one with the latest `virtualenv`.

**Comment by gaborbernat** [comment]
Now should be ok on our side.

**Comment by 2m** [comment]
I saw this error again yesterday when activating venv in VS Code terminal when using fish. FWIW it works fine if I start tmux first.

**Comment by balopat** [comment]
Yeah this is still an issue - https://github.com/pypa/virtualenv/issues/480#issuecomment-285003214 is the right direction. 
Easy to reproduce: 
1. activate virtualenv 
2. `exec fish` 
3. activate virtualenv again 

Fix: before `exec`, `deactivate`

**Comment by gaborbernat** [comment]
What fish version?

**Comment by balopat** [comment]
> What fish version?

```
$ fish -version 
fish, version 3.1.2
```

**Comment by gaborbernat** [comment]
Made a new issue under #1991
