### ISSUE TITLE
virtualenv fails to create virtual environment from Homebrew-installed Python 3.4.3

### ISSUE THREAD

**Issue by aarzee** [pypa/virtualenv#779]
When I try to create a virtual environment with Python 3.4.3, `virtualenv` errors out:

```
Running virtualenv with interpreter /usr/local/bin/python3.4
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 23, in <module>
    import subprocess
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 405, in <module>
    import _posixsubprocess
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/_posixsubprocess.so, 2): Symbol not found: _PyString_AsString
  Referenced from: /usr/local/lib/python2.7/site-packages/_posixsubprocess.so
  Expected in: flat namespace
 in /usr/local/lib/python2.7/site-packages/_posixsubprocess.so
```

I've found another reference to the exact same error [on StackOverflow](http://stackoverflow.com/questions/29911318/error-when-setting-up-virtualenv-with-python-3), with the only answer suggesting to add the `--no-site-packages` argument. Looking through `virtualenv -h`, I see that not only is it deprecated, it doesn't change the setting, as its functionality is currently the default. Predictably, this does not help.

**Comment by tdsmith** [comment]
What's your PYTHONPATH look like? It looks like the problem is that your python 3 is loading modules built for python 2.7.

**Comment by ionelmc** [comment]
Seems similar to https://github.com/pypa/virtualenv/issues/705

**Comment by aarzee** [comment]
Doing `echo $PYTHONPATH` resulted in a blank line.

**Comment by Ivoz** [comment]
@aarzee would appreciate if you could check if above commit solves the issue

**Comment by aarzee** [comment]
Unfortunately, yesterday I upgraded to El Capitan, and pyenv is failing to install 3.4.3 (which is now unavailable via Homebrew). I can't reproduce the bug with current PyPI virtualenv when making a Python 3.5 environment.

**Comment by vmarquet** [comment]
I'm having the exact same issue, can someone please reopen?

```
$ virtualenv -p /usr/local/bin/python3 test
Running virtualenv with interpreter /usr/local/bin/python3
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 27, in <module>
    import subprocess
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 405, in <module>
    import _posixsubprocess
ImportError: dlopen(/Library/Python/2.7/site-packages/_posixsubprocess.so, 2): Symbol not found: _PyString_AsString
  Referenced from: /Library/Python/2.7/site-packages/_posixsubprocess.so
  Expected in: flat namespace
 in /Library/Python/2.7/site-packages/_posixsubprocess.so
```

Other details:

* Mac OS X, 10.11.6
* `$ echo $PYTHONPATH` => `/Library/Python/2.7/site-packages:`

**Comment by vmarquet** [comment]
Problem solved, it was due to Homebrew. It was solved with the following commands:

```
$ brew unlink python3
$ brew link --overwrite  python3
$ unset PYTHONPATH
```

After that, `virtualenv` worked as expected.

**Comment by tdsmith** [comment]
`unset PYTHONPATH` should have been sufficient; Homebrew didn't contribute
to the problem.

**Comment by vmarquet** [comment]
No, I tried `unset PYTHONPATH` before and it didn't solved the problem. After `unset PYTHONPATH`, the error message was different, and related to homebrew problems.

**Comment by BenjaminHCCarr** [comment]
Sadly I am still getting this error, command I am firing off:
`benc$ virtualenv --no-site-packages --distribute --relocatable -p /usr/local/bin/python3 --always-copy .env`

Error:
```
benc$ virtualenv --no-site-packages --distribute --relocatable -p /usr/local/bin/python3 --always-copy .env
Running virtualenv with interpreter /usr/local/bin/python3
The environment doesn't have a file /Users/benc/Code/git/Mine/oh-data-google-fit/.env/bin/activate_this.py -- please re-run virtualenv on this environment to update it
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 700, in main
    make_environment_relocatable(home_dir)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1588, in make_environment_relocatable
    fixup_scripts(home_dir, bin_dir)
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1610, in fixup_scripts
    for filename in os.listdir(bin_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/benc/Code/git/Mine/oh-data-google-fit/.env/bin'
```

I tried `unset PYTHONPATH`; no luck, then tried:
```
benc$ brew unlink python3
Unlinking /usr/local/Cellar/python3/3.6.0... 23 symlinks removed
tyr:~/Code/git/Mine/oh-data-google-fit benc$ brew link --overwrite python3
Linking /usr/local/Cellar/python3/3.6.0... 23 symlinks created
tyr:~/Code/git/Mine/oh-data-google-fit benc$ unset PYTHONPATH
```

Same error.
```
tyr:~/Code/git/Mine/oh-data-google-fit benc$ which python3
/usr/local/bin/python3
tyr:~/Code/git/Mine/oh-data-google-fit benc$ ls -l `!!`
ls -l `which python3`
lrwxr-xr-x  1 benc  admin  35 Jan 23 14:16 /usr/local/bin/python3 -> ../Cellar/python3/3.6.0/bin/python3
```

```
tyr:~/Code/git/Mine/oh-data-google-fit benc$ echo $PYTHONPATH

tyr:~/Code/git/Mine/oh-data-google-fit benc$
```

Thoughts?

**Comment by BenjaminHCCarr** [comment]
Okay, problem found, it was the `--relocatable` with Python3, maybe it was deprecated.

```
benc$ virtualenv --no-site-packages --distribute -p /usr/local/bin/python3 --always-copy .env_OH_GFit
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/benc/Code/git/Mine/oh-data-google-fit/.env_OH_GFit/bin/python3.6
Also creating executable in /Users/benc/Code/git/Mine/oh-data-google-fit/.env_OH_GFit/bin/python
Installing setuptools, pip, wheel...done.
```

worked fine.

**Comment by yardinicwaller** [comment]
A different solution worked for me. I'm using Mac OS X 10.12.3 and python3.5 installed from a package obtained from python.org.
```
pip3 install virtualenv
export PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:$PATH"
```
